-- TPFinal Grupo 155 - Esquema PostgreSQL
-- MVP: un profesional, una agenda, Paciente como entidad independiente y Servicios reservables.

CREATE TABLE profesional (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    apellido VARCHAR(100) NOT NULL,
    telefono VARCHAR(50),
    email VARCHAR(150) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE agenda (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    profesional_id BIGINT NOT NULL UNIQUE,
    CONSTRAINT fk_agenda_profesional
        FOREIGN KEY (profesional_id) REFERENCES profesional(id) ON DELETE RESTRICT
);

CREATE TABLE agenda_config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dia_semana VARCHAR(20) NOT NULL
        CHECK (dia_semana IN ('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY')),
    hora_inicio TIME NOT NULL,
    hora_fin TIME NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    agenda_id BIGINT NOT NULL,
    CONSTRAINT chk_agenda_config_horario CHECK (hora_fin > hora_inicio),
    CONSTRAINT fk_agenda_config_agenda
        FOREIGN KEY (agenda_id) REFERENCES agenda(id) ON DELETE RESTRICT
);

CREATE TABLE excepcion_agenda (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_inicio DATE NOT NULL,
    fecha_fin DATE NOT NULL,
    motivo VARCHAR(255),
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    agenda_id BIGINT NOT NULL,
    CONSTRAINT chk_excepcion_fechas CHECK (fecha_fin >= fecha_inicio),
    CONSTRAINT fk_excepcion_agenda
        FOREIGN KEY (agenda_id) REFERENCES agenda(id) ON DELETE RESTRICT
);

CREATE TABLE paciente (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    apellido VARCHAR(100) NOT NULL,
    telefono VARCHAR(50) NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE servicio (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(120) NOT NULL,
    descripcion VARCHAR(500),
    duracion_minutos INTEGER NOT NULL,
    precio NUMERIC(12,2) NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    profesional_id BIGINT NOT NULL,
    CONSTRAINT chk_servicio_duracion CHECK (duracion_minutos > 0),
    CONSTRAINT chk_servicio_precio CHECK (precio >= 0),
    CONSTRAINT fk_servicio_profesional
        FOREIGN KEY (profesional_id) REFERENCES profesional(id) ON DELETE RESTRICT
);

CREATE TABLE turno (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_hora_inicio TIMESTAMPTZ NOT NULL,
    fecha_hora_fin TIMESTAMPTZ NOT NULL,
    estado VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE'
        CHECK (estado IN ('PENDIENTE', 'CONFIRMADO', 'CANCELADO', 'REALIZADO', 'AUSENTE')),
    observaciones VARCHAR(500),
    acepta_recordatorio_whatsapp BOOLEAN NOT NULL DEFAULT FALSE,
    recordatorio_enviado BOOLEAN NOT NULL DEFAULT FALSE,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    agenda_id BIGINT NOT NULL,
    paciente_id BIGINT NOT NULL,
    servicio_id BIGINT NOT NULL,
    CONSTRAINT chk_turno_horario CHECK (fecha_hora_fin > fecha_hora_inicio),
    CONSTRAINT fk_turno_agenda
        FOREIGN KEY (agenda_id) REFERENCES agenda(id) ON DELETE RESTRICT,
    CONSTRAINT fk_turno_paciente
        FOREIGN KEY (paciente_id) REFERENCES paciente(id) ON DELETE RESTRICT,
    CONSTRAINT fk_turno_servicio
        FOREIGN KEY (servicio_id) REFERENCES servicio(id) ON DELETE RESTRICT
);

-- Regla del MVP:
-- la hora de fin del turno se calcula en el backend a partir de la duración del servicio elegido.

-- Zona horaria:
-- fecha_hora_inicio y fecha_hora_fin son TIMESTAMPTZ (con zona) porque un turno es un
-- instante real en el calendario y el despliegue (Railway) corre en UTC. Guardarlas como
-- TIMESTAMP sin zona haría que un turno de las 10:00 se corra al cambiar de huso.
-- En cambio agenda_config.hora_inicio/hora_fin siguen siendo TIME y las fechas de
-- excepcion_agenda siguen siendo DATE: describen un horario o un día local, sin instante.

-- Evita dos turnos activos con la misma hora de inicio en la misma agenda.
-- Los solapamientos con distintos horarios de inicio también se validarán desde el backend.
CREATE UNIQUE INDEX uq_turno_agenda_inicio_activo
    ON turno (agenda_id, fecha_hora_inicio)
    WHERE estado IN ('PENDIENTE', 'CONFIRMADO');

-- Índices de apoyo para consultas habituales.
CREATE INDEX idx_turno_agenda_fecha
    ON turno (agenda_id, fecha_hora_inicio);

CREATE INDEX idx_paciente_telefono
    ON paciente (telefono);

CREATE INDEX idx_turno_paciente
    ON turno (paciente_id, fecha_hora_inicio);

CREATE INDEX idx_servicio_profesional
    ON servicio (profesional_id, activo);

CREATE INDEX idx_turno_servicio
    ON turno (servicio_id, fecha_hora_inicio);

-- DEFAULT CURRENT_TIMESTAMP solo se aplica al insertar: sin esto la columna
-- quedaría congelada con el valor de la creación en cada update.
-- Esto es "última modificación", no auditoría: no registra quién cambió ni qué.
CREATE OR REPLACE FUNCTION set_turno_fecha_actualizacion() RETURNS trigger AS $$
BEGIN
    NEW.fecha_actualizacion := CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_turno_fecha_actualizacion
    BEFORE UPDATE ON turno
    FOR EACH ROW
    EXECUTE FUNCTION set_turno_fecha_actualizacion();

-- Matriz de transiciones de estado.
--   PENDIENTE  -> CONFIRMADO, CANCELADO
--   CONFIRMADO -> REALIZADO, AUSENTE, CANCELADO
--   CANCELADO, REALIZADO y AUSENTE son terminales: no admiten salida.
-- No se admite CONFIRMADO -> PENDIENTE (desconfirmar ensucia el historial del paciente)
-- ni reabrir un turno terminal. Reprogramar (cambiar fecha_hora_inicio) sí se permite
-- mientras el turno esté en PENDIENTE o CONFIRMADO.
CREATE OR REPLACE FUNCTION valida_turno_transicion_estado() RETURNS trigger AS $$
BEGIN
    IF NEW.estado IS DISTINCT FROM OLD.estado
       AND NOT (
            (OLD.estado = 'PENDIENTE'  AND NEW.estado IN ('CONFIRMADO', 'CANCELADO'))
         OR (OLD.estado = 'CONFIRMADO' AND NEW.estado IN ('REALIZADO', 'AUSENTE', 'CANCELADO'))
       ) THEN
        RAISE EXCEPTION 'Transicion de estado invalida en turno %: % -> %', OLD.id, OLD.estado, NEW.estado
            USING ERRCODE = 'check_violation';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_turno_transicion_estado
    BEFORE UPDATE ON turno
    FOR EACH ROW
    EXECUTE FUNCTION valida_turno_transicion_estado();

-- Cierre automatico de reservas nunca confirmadas.
-- Un turno PENDIENTE cuya hora de fin ya paso queda indistinguible de uno vigente: ensucia
-- el historial del paciente y el reporte de recordatorios. El backend la invoca en forma
-- periodica (@Scheduled) y devuelve cuantos turnos cerro.
-- Consecuencia asumida: al cerrar al pasar la hora, un turno pasado ya no se puede confirmar,
-- por lo que en el historial figura como CANCELADO y nunca como AUSENTE.
CREATE OR REPLACE FUNCTION fn_cerrar_turnos_vencidos() RETURNS bigint AS $$
DECLARE
    cerrados bigint;
BEGIN
    UPDATE turno
    SET estado = 'CANCELADO',
        observaciones = COALESCE(observaciones, '')
            || CASE WHEN observaciones IS NULL OR observaciones = '' THEN '' ELSE E'\n' END
            || 'Cerrado automaticamente: no confirmado antes de la hora del turno'
    WHERE estado = 'PENDIENTE'
      AND fecha_hora_fin < now();
    GET DIAGNOSTICS cerrados = ROW_COUNT;
    RETURN cerrados;
END;
$$ LANGUAGE plpgsql;
