-- TPFinal Grupo 155 - Esquema PostgreSQL
-- MVP: un profesional, una agenda, Paciente como entidad independiente
-- y Servicios reservables.

CREATE TABLE profesional (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    apellido VARCHAR(100) NOT NULL,
    telefono VARCHAR(50),
    email VARCHAR(150) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE agenda (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    profesional_id BIGINT NOT NULL UNIQUE,
    CONSTRAINT fk_agenda_profesional
        FOREIGN KEY (profesional_id)
        REFERENCES profesional(id)
        ON DELETE RESTRICT
);

CREATE TABLE agenda_config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dia_semana VARCHAR(20) NOT NULL
        CHECK (
            dia_semana IN (
                'MONDAY',
                'TUESDAY',
                'WEDNESDAY',
                'THURSDAY',
                'FRIDAY',
                'SATURDAY',
                'SUNDAY'
            )
        ),
    hora_inicio TIME NOT NULL,
    hora_fin TIME NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    agenda_id BIGINT NOT NULL,

    CONSTRAINT chk_agenda_config_horario
        CHECK (hora_fin > hora_inicio),

    CONSTRAINT fk_agenda_config_agenda
        FOREIGN KEY (agenda_id)
        REFERENCES agenda(id)
        ON DELETE RESTRICT
);

CREATE TABLE excepcion_agenda (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_inicio DATE NOT NULL,
    fecha_fin DATE NOT NULL,
    motivo VARCHAR(255),
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    agenda_id BIGINT NOT NULL,

    CONSTRAINT chk_excepcion_fechas
        CHECK (fecha_fin >= fecha_inicio),

    CONSTRAINT fk_excepcion_agenda
        FOREIGN KEY (agenda_id)
        REFERENCES agenda(id)
        ON DELETE RESTRICT
);

CREATE TABLE paciente (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    apellido VARCHAR(100) NOT NULL,
    telefono VARCHAR(50) NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE servicio (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(120) NOT NULL,
    descripcion VARCHAR(500),
    duracion_minutos INTEGER NOT NULL,
    precio NUMERIC(12,2) NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    profesional_id BIGINT NOT NULL,

    CONSTRAINT chk_servicio_duracion
        CHECK (duracion_minutos > 0),

    CONSTRAINT chk_servicio_precio
        CHECK (precio >= 0),

    CONSTRAINT fk_servicio_profesional
        FOREIGN KEY (profesional_id)
        REFERENCES profesional(id)
        ON DELETE RESTRICT
);

CREATE TABLE turno (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_hora_inicio TIMESTAMPTZ NOT NULL,
    fecha_hora_fin TIMESTAMPTZ NOT NULL,

    estado VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE'
        CHECK (
            estado IN (
                'PENDIENTE',
                'CONFIRMADO',
                'CANCELADO',
                'REALIZADO',
                'AUSENTE'
            )
        ),

    observaciones VARCHAR(500),
    acepta_recordatorio_whatsapp BOOLEAN NOT NULL DEFAULT FALSE,
    recordatorio_enviado BOOLEAN NOT NULL DEFAULT FALSE,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    agenda_id BIGINT NOT NULL,
    paciente_id BIGINT NOT NULL,
    servicio_id BIGINT NOT NULL,

    CONSTRAINT chk_turno_horario
        CHECK (fecha_hora_fin > fecha_hora_inicio),

    CONSTRAINT fk_turno_agenda
        FOREIGN KEY (agenda_id)
        REFERENCES agenda(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_turno_paciente
        FOREIGN KEY (paciente_id)
        REFERENCES paciente(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_turno_servicio
        FOREIGN KEY (servicio_id)
        REFERENCES servicio(id)
        ON DELETE RESTRICT
);

-- RELACION PROFESIONAL - AGENDA
--
-- agenda.profesional_id es NOT NULL y UNIQUE.
--
-- Esto garantiza que:
-- 1. toda agenda pertenece exactamente a un profesional;
-- 2. un profesional puede tener como máximo una agenda.
--
-- La creación de la agenda correspondiente al profesional se garantiza
-- desde la lógica de la aplicación.

-- ESTADO DEL TURNO
--
-- En PostgreSQL se almacena como VARCHAR con una restricción CHECK.
-- En el backend se representa mediante el enum EstadoTurno.

-- DURACION DEL TURNO
--
-- La hora de finalización se calcula en el backend a partir de
-- servicio.duracion_minutos y luego se almacena en
-- turno.fecha_hora_fin.

-- ZONA HORARIA
--
-- fecha_hora_inicio y fecha_hora_fin son TIMESTAMPTZ porque un turno
-- representa un instante real en el calendario y el despliegue puede
-- ejecutarse en UTC.
--
-- fecha_creacion y fecha_actualizacion también utilizan TIMESTAMPTZ.
--
-- agenda_config.hora_inicio y agenda_config.hora_fin siguen siendo TIME,
-- mientras que excepcion_agenda.fecha_inicio y fecha_fin utilizan DATE,
-- porque representan horarios y fechas locales de atención.

-- Evita dos turnos activos con la misma hora de inicio dentro de la
-- misma agenda.
--
-- Los solapamientos con diferentes horas de inicio también se validan
-- desde el backend.
CREATE UNIQUE INDEX uq_turno_agenda_inicio_activo
    ON turno (agenda_id, fecha_hora_inicio)
    WHERE estado IN ('PENDIENTE', 'CONFIRMADO');

-- Índices de apoyo para consultas habituales.

CREATE INDEX idx_turno_agenda_fecha
    ON turno (agenda_id, fecha_hora_inicio);

CREATE INDEX idx_paciente_telefono
    ON paciente (telefono);

CREATE INDEX idx_turno_paciente
    ON turno (paciente_id, fecha_hora_inicio);

CREATE INDEX idx_servicio_profesional
    ON servicio (profesional_id, activo);

CREATE INDEX idx_turno_servicio
    ON turno (servicio_id, fecha_hora_inicio);

-- ULTIMA MODIFICACION DEL TURNO
--
-- DEFAULT CURRENT_TIMESTAMP sólo se aplica al insertar.
-- Este trigger actualiza fecha_actualizacion en cada UPDATE.
--
-- Representa la última modificación del registro y no constituye
-- un mecanismo completo de auditoría.

CREATE OR REPLACE FUNCTION set_turno_fecha_actualizacion()
RETURNS trigger AS $$
BEGIN
    NEW.fecha_actualizacion := CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_turno_fecha_actualizacion
    BEFORE UPDATE ON turno
    FOR EACH ROW
    EXECUTE FUNCTION set_turno_fecha_actualizacion();

-- TRANSICIONES DE ESTADO
--
-- PENDIENTE  -> CONFIRMADO, CANCELADO
-- CONFIRMADO -> REALIZADO, AUSENTE, CANCELADO
--
-- CANCELADO, REALIZADO y AUSENTE son estados terminales.
--
-- No se admite CONFIRMADO -> PENDIENTE ni la reapertura de un turno
-- que ya se encuentra en un estado terminal.
--
-- La reprogramación de fecha y horario se permite desde la lógica del
-- backend únicamente mientras el turno esté PENDIENTE o CONFIRMADO.

CREATE OR REPLACE FUNCTION valida_turno_transicion_estado()
RETURNS trigger AS $$
BEGIN
    IF NEW.estado IS DISTINCT FROM OLD.estado
       AND NOT (
            (OLD.estado = 'PENDIENTE'
                AND NEW.estado IN ('CONFIRMADO', 'CANCELADO'))
         OR
            (OLD.estado = 'CONFIRMADO'
                AND NEW.estado IN ('REALIZADO', 'AUSENTE', 'CANCELADO'))
       )
    THEN
        RAISE EXCEPTION
            'Transicion de estado invalida en turno %: % -> %',
            OLD.id,
            OLD.estado,
            NEW.estado
            USING ERRCODE = 'check_violation';
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_turno_transicion_estado
    BEFORE UPDATE ON turno
    FOR EACH ROW
    EXECUTE FUNCTION valida_turno_transicion_estado();

-- CIERRE AUTOMATICO DE RESERVAS VENCIDAS
--
-- Un turno PENDIENTE cuya hora de finalización ya pasó se considera
-- una reserva que nunca fue confirmada.
--
-- El backend puede ejecutar esta función periódicamente mediante una
-- tarea programada.
--
-- Los turnos encontrados pasan a CANCELADO y se deja constancia en
-- observaciones.
--
-- La función devuelve la cantidad de turnos cerrados.

CREATE OR REPLACE FUNCTION fn_cerrar_turnos_vencidos()
RETURNS bigint AS $$
DECLARE
    cerrados bigint;
BEGIN
    UPDATE turno
    SET estado = 'CANCELADO',
        observaciones =
            COALESCE(observaciones, '')
            || CASE
                WHEN observaciones IS NULL OR observaciones = ''
                    THEN ''
                ELSE E'\n'
               END
            || 'Cerrado automaticamente: no confirmado antes de la hora del turno'
    WHERE estado = 'PENDIENTE'
      AND fecha_hora_fin < now();

    GET DIAGNOSTICS cerrados = ROW_COUNT;

    RETURN cerrados;
END;
$$ LANGUAGE plpgsql;