-- TPFinal Grupo 155 - Esquema PostgreSQL
-- MVP: un profesional, una agenda, Paciente como entidad independiente y Servicios reservables.

CREATE TABLE profesional (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    apellido VARCHAR(100) NOT NULL,
    telefono VARCHAR(50),
    email VARCHAR(150) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE agenda (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    profesional_id BIGINT NOT NULL UNIQUE,
    CONSTRAINT fk_agenda_profesional
        FOREIGN KEY (profesional_id) REFERENCES profesional(id) ON DELETE RESTRICT
);

CREATE TABLE agenda_config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dia_semana VARCHAR(20) NOT NULL
        CHECK (dia_semana IN ('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY')),
    hora_inicio TIME NOT NULL,
    hora_fin TIME NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    agenda_id BIGINT NOT NULL,
    CONSTRAINT chk_agenda_config_horario CHECK (hora_fin > hora_inicio),
    CONSTRAINT fk_agenda_config_agenda
        FOREIGN KEY (agenda_id) REFERENCES agenda(id) ON DELETE RESTRICT
);

CREATE TABLE excepcion_agenda (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_inicio DATE NOT NULL,
    fecha_fin DATE NOT NULL,
    motivo VARCHAR(255),
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    agenda_id BIGINT NOT NULL,
    CONSTRAINT chk_excepcion_fechas CHECK (fecha_fin >= fecha_inicio),
    CONSTRAINT fk_excepcion_agenda
        FOREIGN KEY (agenda_id) REFERENCES agenda(id) ON DELETE RESTRICT
);

CREATE TABLE paciente (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    apellido VARCHAR(100) NOT NULL,
    telefono VARCHAR(50) NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE servicio (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(120) NOT NULL,
    descripcion VARCHAR(500),
    duracion_minutos INTEGER NOT NULL,
    precio NUMERIC(12,2) NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    profesional_id BIGINT NOT NULL,
    CONSTRAINT chk_servicio_duracion CHECK (duracion_minutos > 0),
    CONSTRAINT chk_servicio_precio CHECK (precio >= 0),
    CONSTRAINT fk_servicio_profesional
        FOREIGN KEY (profesional_id) REFERENCES profesional(id) ON DELETE RESTRICT
);

CREATE TABLE turno (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_hora_inicio TIMESTAMP NOT NULL,
    fecha_hora_fin TIMESTAMP NOT NULL,
    estado VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE'
        CHECK (estado IN ('PENDIENTE', 'CONFIRMADO', 'CANCELADO')),
    observaciones VARCHAR(500),
    acepta_recordatorio_whatsapp BOOLEAN NOT NULL DEFAULT FALSE,
    recordatorio_enviado BOOLEAN NOT NULL DEFAULT FALSE,
    agenda_id BIGINT NOT NULL,
    paciente_id BIGINT NOT NULL,
    servicio_id BIGINT NOT NULL,
    CONSTRAINT chk_turno_horario CHECK (fecha_hora_fin > fecha_hora_inicio),
    CONSTRAINT fk_turno_agenda
        FOREIGN KEY (agenda_id) REFERENCES agenda(id) ON DELETE RESTRICT,
    CONSTRAINT fk_turno_paciente
        FOREIGN KEY (paciente_id) REFERENCES paciente(id) ON DELETE RESTRICT,
    CONSTRAINT fk_turno_servicio
        FOREIGN KEY (servicio_id) REFERENCES servicio(id) ON DELETE RESTRICT
);

-- Regla del MVP:
-- la hora de fin del turno se calcula en el backend a partir de la duración del servicio elegido.

-- Evita dos turnos activos con la misma hora de inicio en la misma agenda.
-- Los solapamientos con distintos horarios de inicio también se validarán desde el backend.
CREATE UNIQUE INDEX uq_turno_agenda_inicio_activo
    ON turno (agenda_id, fecha_hora_inicio)
    WHERE estado IN ('PENDIENTE', 'CONFIRMADO');

-- Índices de apoyo para consultas habituales.
CREATE INDEX idx_turno_agenda_fecha
    ON turno (agenda_id, fecha_hora_inicio);

CREATE INDEX idx_paciente_telefono
    ON paciente (telefono);

CREATE INDEX idx_turno_paciente
    ON turno (paciente_id, fecha_hora_inicio);

CREATE INDEX idx_servicio_profesional
    ON servicio (profesional_id, activo);

CREATE INDEX idx_turno_servicio
    ON turno (servicio_id, fecha_hora_inicio);
